### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ronnie173** [kasem-sm/DynamicLinksPlayground#1]
Hi do you know how to get this to work for Android 33? I am having problems because it says that the "Access blocked: ComponentInfo{"

**Comment by kasem-sm** [comment]
> Hi do you know how to get this to work for Android 33? I am having problems because it says that the "Access blocked: ComponentInfo{"

Hey. You can refer this question on [stackOverFlow](https://stackoverflow.com/questions/73495596/unable-to-launch-arbitrary-activity-since-android-13) as of now.
